# Numpy Library

- **Source 1 (All):** https://www.youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK
- **Source 2 (First 4 Videos of numpy videos):** https://www.youtube.com/playlist?list=PL6-3IRz2XF5UM-FWfQeF1_YhMMa12Eg3s

In [1]:
import numpy as np

#### Trigonometric Functions : -

1. **`np.tan(angle_in_degree):`** 
   - Calculate the sin of the angle
2. **`np.cos(angle_in_degree):`** 
   - Calculate the cos of the angle
3. **`np.tan(angle_in_degree):`**
   - Calculate the tan of the angle

In [2]:

print(np.sin(30))
print(np.cos(30))
print(np.tan(30))

-0.9880316240928618
0.15425144988758405
-6.405331196646276


#### NumPy Round Function:

1. **`np.round(value)`**:
   - This function rounds a floating-point number to the nearest integer. If the decimal part is `.5` or greater, it rounds up; otherwise, it rounds down.

2. **`np.round(value, decimals)`**:
   - This function rounds a floating-point number to a specified number of decimal places. The `decimals` parameter indicates how many digits to keep after the decimal point. 

In [3]:
print(np.round(3.123456)) # approximate to the integer
print(np.round(3.123456,2)) # approximate to the second decimal number
print(np.round(3.123456,3)) # approximate to the third decimal number


3.0
3.12
3.123


#### NumPy Floor and Ceil Functions:

1. **`np.floor(value)`**:
   - This function returns the largest integer less than or equal to the given floating-point number. It effectively rounds down to the nearest whole number.

2. **`np.ceil(value)`**:
   - This function returns the smallest integer greater than or equal to the given floating-point number. It effectively rounds up to the nearest whole number.

In [4]:
print(f"floor : {np.floor(3.99999999999)}")
print(f"ceil : {np.ceil(3.000000000000001)}")

floor : 3.0
ceil : 4.0


### NumPy 2D Array (Matrix):

1. **Creating a 2D Array**:
   - **`np.array([[1, 2], [3, 4]])`**: This function creates a 2-dimensional NumPy array (matrix) with the specified elements. In this case, it forms a matrix with two rows and two columns.

2. **Error with Inconsistent Row Lengths**:
   - **`np.array([[1, 2], [3, 4], [5, 6, 7]])`**: This will raise an error because the inner lists (rows) do not have the same length. NumPy requires that all rows in a 2D array have the same number of elements to maintain a rectangular shape. The first two rows have two elements each, while the last row has three elements, resulting in a shape inconsistency.


In [5]:
matrix_2d = np.array([[1,2],[3,4]])
print(matrix_2d)
# error 
#  np.array([[1,2],[3,4],[5,6,7]])
# 


[[1 2]
 [3 4]]


### NumPy Empty Matrix:

1. **`np.empty((3, 2))`**:
   - This function creates a 3x2 matrix (3 rows and 2 columns) without initializing the values. The contents of the matrix will be random, often containing residual data from memory, so the numbers may seem arbitrary or unpredictable.
   - The `empty()` function is useful when you want to quickly create an array with a specific shape and then populate it with values later. However, since it doesn’t initialize elements, it is not suitable for cases where you need a clean, zeroed-out matrix.

In [6]:
empty_matrix = np.empty((3,2))
print(empty_matrix)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 2.67022274e-307]
 [2.67018234e-306 5.56268465e-309]]


### NumPy `uniform` Function:

1. **`np.random.uniform(1, 10)`**:
   - This generates a single random floating-point number within the range `[1, 10)`. The number is chosen from a continuous uniform distribution, meaning each number in this interval has an equal chance of being selected.

2. **`np.random.uniform(1, 10, 20)`**:
   - This generates an array of 20 random floating-point numbers, each within the range `[1, 10)`. Each element in the array is independently drawn from the same uniform distribution.

The `uniform` function is useful when you need a sequence or array of random numbers within a specific range for simulations, statistical sampling, or randomized algorithms.

In [11]:
a = np.random.uniform(1,10) # create a random number from 1 to 10
print(a)
b = np.random.uniform(1,10,20) # create a list of 20 random numbers from 1 to 10
print(b)

2.735567517524829
[6.65691623 3.82849982 3.81440439 3.39892802 5.53914473 7.58424278
 2.69836417 7.50891913 7.98223053 2.39901206 5.91614151 8.77998812
 2.50415973 7.77157168 9.32170454 3.02469416 1.22577592 8.11138948
 7.50832828 7.92794805]


### NumPy `random` Function for 2D Array:

1. **`np.random.random((2, 3))`**:
   - This function generates a 2D array (matrix) with the specified shape, in this case, 2 rows and 3 columns.
   - Each element in the array is a random floating-point number drawn from a uniform distribution over the range `[0, 1)`, where each number is equally likely to appear.

The `random` function is useful for creating matrices of random values for testing algorithms, simulations, and for initializing values in machine learning models.

In [13]:
rand_matrix1 = np.random.random((2,3)) # create a 2d array of 3 random numbers with range 0 ~ 1
print(rand_matrix1)

[[0.32898496 0.49943776 0.55264911]
 [0.55599364 0.01199098 0.46096088]]


### NumPy `randint` Function for Random Integer Arrays and Reshaping:

1. **`np.random.randint(15)`**:
   - Generates a single random integer from `0` up to `14`.

2. **`np.random.randint(15, 30)`**:
   - Generates a single random integer from `15` up to `29`.

3. **`np.random.randint(15, 30, size=10)`**:
   - Creates an array of 10 random integers, each between `15` and `29`.

4. **`np.random.randint(15, 30, (3, 3))`**:
   - Generates a `3x3` matrix where each element is a random integer between `15` and `29`.

5. **`np.random.randint(15, 30, (3, 3, 3))`**:
   - Creates a `3x3x3` 3D matrix where each element is a random integer between `15` and `29`. This 3D matrix consists of 3 layers of `3x3` matrices.

6. **`np.reshape()` with `randint`**:
   - **`np.random.randint(15, 30, size=10)`** generates a 1D array of 10 random integers between `15` and `29`.
   - **`np.reshape(array, (2, 5))`** reshapes this 1D array into a `2x5` matrix, with 2 rows and 5 columns.


In [18]:
rand_int1 = np.random.randint(15) # create a random integer number from 0 to 15
print(rand_int1)
rand_int2 = np.random.randint(15,30) # create a random integer number from 15 to 30
print(rand_int2)
rand_int3 = np.random.randint(15,30,size=10) # create 10 random integers number from 15 to 30
print(rand_int3)
rand_int4 = np.random.randint(15,30,(3,3)) # create 3x3 matrix with random integers number from 15 to 30
print(rand_int4)
rand_int5 = np.random.randint(15,30,(3,3,3)) # create 3x3x3 matrix with random integers number from 15 to 30
print(rand_int5)
rand_int_6 = np.random.randint(15,30,size=10) # create 10 random integers number from 15 to 30
rand_int_reshape = np.reshape(rand_int_6,(2,5)) # reshape the list to 2x5 matrix
print(rand_int_reshape)

3
27
[22 15 19 25 25 29 25 26 20 27]
[[15 23 21]
 [20 21 27]
 [20 27 25]]
[[[20 16 28]
  [22 19 27]
  [16 17 27]]

 [[19 16 23]
  [22 19 16]
  [29 28 20]]

 [[28 22 20]
  [22 24 29]
  [23 21 23]]]
[[20 29 25 28 25]
 [15 19 29 25 24]]


### NumPy `rand` Function for Random Float Arrays:

1. **`np.random.rand(5)`**:
   - This creates a 1D array of 5 random floating-point numbers, each within the range `[0, 1)`. Each element is independently chosen from a uniform distribution over this interval.

2. **`np.random.rand(2, 5)`**:
   - This generates a 2D array with 2 rows and 5 columns, where each element is a random floating-point number between `0` and `1`.

3. **`np.random.rand(3, 2, 5)`**:
   - This creates a 3D array with a shape of `3x2x5`, meaning it contains 3 layers of `2x5` arrays. Each element in this 3D array is a random float between `0` and `1`.

The `rand` function is useful for generating arrays filled with random floats within the `[0, 1)` range, with flexible control over the array’s shape and dimensions.

In [20]:
rand_float1 = np.random.rand(5)
print(rand_float1)
rand_float2 = np.random.rand(2,5)
print(rand_float2)
rand_float3 = np.random.rand(3,2,5)
print(rand_float3)

[0.59500334 0.61532703 0.5082549  0.62487352 0.49469936]
[[0.32030854 0.61233783 0.45932203 0.65363069 0.26825666]
 [0.99580491 0.57159496 0.66390121 0.39695826 0.59901913]]
[[[0.16603339 0.28702515 0.40212848 0.92095833 0.22433287]
  [0.80990145 0.73496429 0.11720421 0.83314948 0.42427883]]

 [[0.49775124 0.12103718 0.97788114 0.96464554 0.47621328]
  [0.11306075 0.29592159 0.83847665 0.35384502 0.54943533]]

 [[0.42111678 0.48593823 0.43735111 0.5321804  0.06630691]
  [0.58004357 0.21543573 0.32339688 0.57645472 0.80330853]]]


### NumPy Random Choice and Shuffle Functions:

1. **`np.random.randint(0, 10, size=10)`**:
   - This creates a 1D array of 10 random integers, each between `0` and `9`.

2. **`np.random.choice(list_1)`**:
   - This function randomly selects a single element from `list_1`.

3. **`np.random.choice(list_1, size=5)`**:
   - This selects 5 random elements from `list_1`, with each selection being independent. If `size=5` is specified, a 1D array of 5 randomly chosen elements is returned.

4. **`np.random.shuffle(list_1)`**:
   - This rearranges the elements in `list_1` randomly, modifying the original array in place. 

These functions are useful for selecting random samples, creating random subsets, and shuffling arrays to add randomness in simulations or randomized algorithms.

In [21]:
list_1 = np.random.randint(0,10,size=10) # create a random list of 10 elements 
print(list_1)
a = np.random.choice(list_1) # choose a random element
print(a)
a = np.random.choice(list_1,size = 5) # choose 5 random elements
print(a)
np.random.shuffle(list_1) # rearrange list_1 randomly
print(list_1)


[6 5 7 6 1 4 4 7 2 8]
8
[6 7 4 6 2]
[2 5 8 4 1 6 7 6 7 4]


### NumPy Functions for Creating Arrays with Specific Values:

1. **`np.zeros`**:
   - **`np.zeros(2)`**: Creates a 1D array with 2 elements, all set to `0`.
   - **`np.zeros((2, 3))`**: Creates a 2D array with 2 rows and 3 columns, all elements set to `0`.
   - **`np.zeros((1, 2, 3))`**: Creates a 3D array with 1 layer, containing 2 rows and 3 columns per row, all elements set to `0`.

2. **`np.ones`**:
   - **`np.ones(2)`**: Creates a 1D array with 2 elements, all set to `1`.
   - **`np.ones((2, 3))`**: Creates a 2D array with 2 rows and 3 columns, all elements set to `1`.
   - **`np.ones((1, 2, 3))`**: Creates a 3D array with 1 layer, containing 2 rows and 3 columns per row, all elements set to `1`.

3. **`np.eye`**:
   - **`np.eye(2)`**: Creates a 2x2 identity matrix, where the diagonal elements are `1` and all other elements are `0`.

4. **`np.full`**:
   - **`np.full(2, 3)`**: Creates a 1D array with 2 elements, each set to `3`.
   - **`np.full((2, 3), 35)`**: Creates a 2D array with 2 rows and 3 columns, with every element set to `35`.

These functions are essential for creating arrays pre-filled with specific values, useful for initialization and setting default states in data processing and matrix operations.

In [23]:
a = np.zeros(2)
print(a)
b = np.zeros((2,3))
print(b)
c = np.zeros((1,2,3))
print(c)

a = np.ones(2)
print(a)
b = np.ones((2,3))
print(b)
c = np.ones((1,2,3))
print(c)

a = np.eye(2)
print(a)
b = np.full(2,3)
print(b)
c = np.full((2,3), 35)
print(c)

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]]
[[1. 0.]
 [0. 1.]]
[3 3]
[[35 35 35]
 [35 35 35]]


### NumPy `arange` and `reshape` Functions:

1. **`np.arange(18)`**:
   - Generates a 1D array containing integers from `0` to `17`. The `arange` function creates evenly spaced values within a specified range.

2. **`np.arange(30)`**:
   - Creates a 1D array containing integers from `0` to `29`.

3. **Reshaping Arrays**:
   - **`a.reshape(3, 6)`**: Reshapes the array `a` into a 2D array with 3 rows and 6 columns. The total number of elements must remain the same (18 in this case).
   - **`b.reshape(2, 3, 5)`**: Reshapes the array `b` into a 3D array with 2 layers, each containing 3 rows and 5 columns. Again, the total number of elements (30) must be preserved.

These functions are useful for generating sequences of numbers and organizing them into different dimensional arrays, allowing for flexible data manipulation and analysis.

In [25]:
a = np.arange(18)
print(a)
b = np.arange(30)
print(b)

a = a.reshape(3,6)
print(a)
b = b.reshape(2,3,5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### NumPy Operations on an Array:

1. **`np.array([-4, -9, 16, 25])`**:
   - This creates a NumPy array named `np1` with the elements `[-4, -9, 16, 25]`.

2. **`print(f"np1 : {np1}")`**:
   - Displays the original array `np1`.

3. **`np.absolute(np1)`**:
   - Calculates the absolute values of each element in `np1`. This function converts negative numbers to positive, resulting in the array `[4, 9, 16, 25]`.

4. **`print(f"absolute np1 : {np.absolute(np1)}")`**:
   - Displays the array of absolute values.

5. **`np.sqrt(np1)`**:
   - Computes the square root of each element in the absolute array. Since all values are non-negative, it returns `[2, 3, 4, 5]`.

6. **`print(f"sqrt : {np.sqrt(np1)}")`**:
   - Displays the square root of the absolute values.

7. **`np.exp(np1)`**:
   - Calculates the exponential (e raised to the power of each element) of `np1`. The output will include both large values for positive inputs and values close to zero for negative inputs.

8. **`print(f"exp np1 : {np.exp(np1)}")`**:
   - Displays the result of the exponential operation on `np1`.

9. **`np.min(np1)`**:
   - Finds the minimum value in `np1`. In this case, it returns `-9`, as it is the smallest element in the original array.

10. **`print(f"min np1 : {np.min(np1)}")`**:
    - Displays the minimum value.

11. **`np.max(np1)`**:
    - Identifies the maximum value in `np1`, which is `25`.

12. **`print(f"max np1 : {np.max(np1)}")`**:
    - Displays the maximum value.

These operations demonstrate the versatility of NumPy for performing various mathematical functions on arrays, providing valuable statistical and mathematical insights into the data.

In [31]:
np1 = np.array([-4,-9,16,25])
print(f"np1 : {np1}")
print(f"absolute np1 : {np.absolute(np1)}")
np1 = np.absolute(np1)
print(f"sqrt : {np.sqrt(np1)}")
print(f"exp np1 : {np.exp(np1)}")
print(f"min np1 : {np.min(np1)}")
print(f"max np1 : {np.max(np1)}")

np1 : [-4 -9 16 25]
absolute np1 : [ 4  9 16 25]
sqrt : [2. 3. 4. 5.]
exp np1 : [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
min np1 : 4
max np1 : 25


## View VS Copy
In NumPy, understanding the difference between a "view" and a "copy" of an array is essential for efficient memory management and avoiding unintended side effects in data manipulation.

**View**:
- A view is a new array that references the same data as the original array.
- When you create a view, any modifications made to the view will affect the original array since they share the same data in memory.
- Views are useful when you want to perform operations on a subset of data without duplicating the entire dataset, thus saving memory.

**Copy**:
- A copy creates a new array that contains the same data as the original but is stored in a separate memory location.
- Changes made to the copy do not affect the original array, and vice versa.
- Copies are helpful when you want to work with data without the risk of modifying the original dataset.

**As an Example**:
**Creating Arrays**:
- `np.array([1, 2, 3, 4, 5, 6])`: This creates a NumPy array named `np1` with the elements `[1, 2, 3, 4, 5, 6]`.

**Creating a View**:
- `np1.view()`: This creates a view of `np1`, which is stored in `np2`. A view is a new array that looks at the same data as the original array. Modifications to the view will affect the original array.

**Creating a Copy**:
- `np1.copy()`: This creates a copy of `np1`, stored in `np3`. A copy is a separate array with its own data. Changes to the copy do not affect the original array.

**Before Editing**:
- The initial state of the arrays is printed, showing:
  - `np1 = [1, 2, 3, 4, 5, 6]`
  - `np2 = [1, 2, 3, 4, 5, 6]` (same as `np1`, since it is a view)
  - `np3 = [1, 2, 3, 4, 5, 6]` (a separate copy)

**Editing the First Element**:
- `np1[0] = 0`: The first element of `np1` is changed from `1` to `0`.

**After Editing**:
- The state of the arrays is printed again, showing:
  - `np1 = [0, 2, 3, 4, 5, 6]` (original array modified)
  - `np2 = [0, 2, 3, 4, 5, 6]` (view reflects the change in `np1`)
  - `np3 = [1, 2, 3, 4, 5, 6]` (copy remains unchanged)

In [33]:
# view vs copy 
np1 = np.array([1,2,3,4,5,6])
np2 = np1.view()
np3 = np1.copy()
print("Before Editing The First Element : ")
print(f"np1 = {np1}")
print(f"np2 = {np2}")
print(f"np3 = {np3}")

#editing the first element
np1[0] = 0

print("******************************************************")
print("After Editing The First Element : ")
print(f"np1 = {np1}")
print(f"np2 = {np2}")
print(f"np3 = {np3}")


Before Editing The First Element : 
np1 = [1 2 3 4 5 6]
np2 = [1 2 3 4 5 6]
np3 = [1 2 3 4 5 6]
******************************************************
After Editing The First Element : 
np1 = [0 2 3 4 5 6]
np2 = [0 2 3 4 5 6]
np3 = [1 2 3 4 5 6]


In NumPy, sorting is a fundamental operation used to arrange the elements of an array in a specified order. This can be applied to various data types, including numbers, strings, and boolean values. The `np.sort()` function is used for this purpose and returns a new array with the sorted elements while keeping the original array unchanged.

### Concept of Sorting in NumPy:
- **Sorting Numbers**: Numeric arrays can be sorted in ascending or descending order, making it easier to analyze or visualize data.
- **Sorting Strings**: String arrays are sorted alphabetically, allowing for organized lists of text data.
- **Sorting Boolean Values**: Boolean arrays are sorted based on their truth values, where `False` is considered less than `True`.
- **Sorting 2D Arrays**: When sorting multi-dimensional arrays, `np.sort()` operates along the specified axis (default is the last axis) and returns a sorted version of the array.

### Examples:
#### Sorting Numbers:
- **Creating an Array**:
  - `np.array([3, 2, 1, 5, 7, 6])`: This creates a NumPy array named `np1` with integer values `[3, 2, 1, 5, 7, 6]`.
- **Sorting Operation**:
  - `np.sort(np1)`: This sorts `np1` in ascending order, resulting in `[1, 2, 3, 5, 6, 7]`.

#### Sorting Alpha (Strings):
- **Creating an Array**:
  - `np.array(["Mohamed", "Ahmed", "Salem", "Mahmoud"])`: This creates a NumPy array named `np2` with string values `["Mohamed", "Ahmed", "Salem", "Mahmoud"]`.
- **Sorting Operation**:
  - `np.sort(np2)`: This sorts the strings in alphabetical order, resulting in `["Ahmed", "Mahmoud", "Mohamed", "Salem"]`.

#### Sorting Boolean Values:
- **Creating an Array**:
  - `np.array([True, False, False, True])`: This creates a NumPy array named `np3` with boolean values `[True, False, False, True]`.
- **Sorting Operation**:
  - `np.sort(np3)`: This sorts the boolean values, resulting in `[False, False, True, True]` since `False` is considered less than `True`.

#### Sorting a 2D Array:
- **Creating a 2D Array**:
  - `np.array([[5, 4, 7, 6], [2, 1, 0, 3]])`: This creates a 2D NumPy array named `np4`.
- **Sorting Operation**:
  - `np.sort(np4)`: This sorts the elements along the last axis (row-wise by default), resulting in:
    ```
    [[4, 5, 6, 7],
     [0, 1, 2, 3]]
    ```
    Each row is sorted independently.

### Summary:
Sorting in NumPy provides an efficient way to organize and analyze data across various data types, including numbers, strings, boolean values, and multi-dimensional arrays. The `np.sort()` function facilitates this process, ensuring that the original data remains intact while providing a new sorted array.

In [37]:
#sorting numbers
np1 = np.array([3,2,1,5,7,6])
print(f"np1 : {np1}")
print(f"np1 sorted : {np.sort(np1)}")

#sorting Alpha
np2 = np.array(["Mohamed","Ahmed","Salem","Mahmoud"])
print(f"np2 : {np2}")
print(f"np2 sorted : {np.sort(np2)}")

#sorting boolean
np3 = np.array([True,False,False,True])
print(f"np3 : {np3}")
print(f"np3 sorted : {np.sort(np3)}")

#sorting 2d-array
np4 = np.array([[5,4,7,6],[2,1,0,3]])
print(f"np4 : {np4}")
print(f"np4 sorted : {np.sort(np4)}")

np1 : [3 2 1 5 7 6]
np1 sorted : [1 2 3 5 6 7]
np2 : ['Mohamed' 'Ahmed' 'Salem' 'Mahmoud']
np2 sorted : ['Ahmed' 'Mahmoud' 'Mohamed' 'Salem']
np3 : [ True False False  True]
np3 sorted : [False False  True  True]
np4 : [[5 4 7 6]
 [2 1 0 3]]
np4 sorted : [[4 5 6 7]
 [0 1 2 3]]


In NumPy, the `np.where()` function is a powerful tool for conditional indexing. It allows you to locate the indices of elements in an array that satisfy a given condition.

### Explanation of the Code:

1. **Creating the Array**:
   - `np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3, 2, 1])`: This creates a NumPy array named `np1` containing the integers from 1 to 10, along with some duplicates.

2. **Finding Indices of a Specific Value**:
   - `np.where(np1 == 3)`: This line checks for elements in `np1` that are equal to `3`. It returns a tuple of arrays, where the first element contains the indices of all occurrences of `3`.

3. **Output of `np.where()`**:
   - `print(f"where output : {x}")`: This prints the output of `np.where()`, which shows the indices of the elements equal to `3`.

4. **Accessing Indices**:
   - `print(f"indicies of elements whose values = 3 : {x[0]}")`: This prints the indices of the elements in `np1` that are equal to `3`.

5. **Retrieving Values from Indices**:
   - `print(f"values of the found elements using the indicies : {np1[x[0]]}")`: This retrieves the actual values from `np1` at the identified indices. It will show the occurrences of `3` in the array.

6. **Finding Even Numbers**:
   - `x = np.where(np1 % 2 == 0)`: This line finds the indices of even numbers in the array by checking if the elements are divisible by `2` without a remainder.

7. **Output of Even Number Indices**:
   - `print(f"the indices of the even numbers : {x[0]}")`: This prints the indices of the even numbers found in `np1`.

8. **Retrieving Even Numbers**:
   - `print(f"the even numbers : {np1[x[0]]}")`: This retrieves the actual even numbers from `np1` using the indices found in the previous step.

### Summary:
The code effectively demonstrates how to use `np.where()` to locate specific values and conditions within a NumPy array. Initially, it identifies and retrieves the occurrences of the number `3`, and then it extends the functionality to find and display even numbers, showcasing the versatility of conditional indexing in data manipulation tasks.

In [43]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3,2,1])
x = np.where(np1 == 3)
print(f"where output : {x}") # the result of where
print(f"indicies of elements whose values = 3 : {x[0]}") # the first element which includes the index
print(f"values of the found elements using the indicies : {np1[x[0]]}") # the actual value (elements at that index)

# exercise : return even numbers
x = np.where(np1 %2 ==0)
print(f"the indices of the even numbers : {x[0]}") # the first element which includes the index
print(f"the even numbers : {np1[x[0]]}") # the actual value (elements at that index)


where output : (array([ 2, 10]),)
indicies of elements whose values = 3 : [ 2 10]
values of the found elements using the indicies : [3 3]
the indices of the even numbers : [ 1  3  5  7  9 11]
the even numbers : [ 2  4  6  8 10  2]


In NumPy, filtering an array allows you to extract elements that meet certain conditions. This can be done using various methods, demonstrating the flexibility and efficiency of NumPy for data manipulation.

### Explanation of the Code:

1. **Creating the Array**:
   - `np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`: This creates a NumPy array named `np1` containing integers from 1 to 10.

2. **Method 1: Manual Filtering with a Boolean List**:
   - `values = [False, True, False, True, False, True, False, True, False, True]`: A boolean list is created where each position corresponds to whether the number at that index in `np1` is even.
   - `print(f"Method 1 : {np1[values]}")`: This filters `np1` using the boolean list, resulting in an array of even numbers: `[2, 4, 6, 8, 10]`.

3. **Method 2: Using Loops for Filtering**:
   - `m2 = []`: An empty list `m2` is initialized to store boolean values.
   - A `for` loop iterates over each element in `np1`. If the element is even (`element % 2 == 0`), `True` is appended to `m2`; otherwise, `False` is appended.
   - `print(f"Method 2 : {np1[m2]}")`: The boolean list `m2` is then used to filter `np1`, producing the same result as Method 1: `[2, 4, 6, 8, 10]`.

4. **Method 3: Vectorized Operation Using NumPy**:
   - `m3 = np1 % 2 == 0`: This line uses NumPy's vectorized operations to create a boolean array `m3` where each element indicates whether the corresponding element in `np1` is even.
   - `print(f"Method 3 : {np1[m3]}")`: Finally, `np1` is filtered using `m3`, yielding the same even numbers: `[2, 4, 6, 8, 10]`.

### Summary:
The code illustrates three different methods for filtering even numbers from a NumPy array:
- **Method 1** demonstrates using a predefined boolean list.
- **Method 2** shows how to achieve filtering with a traditional loop.
- **Method 3** leverages NumPy's ability to handle operations in a vectorized manner, which is typically the most efficient and concise approach.

These methods highlight the flexibility of NumPy in handling array operations and filtering data efficiently.

In [46]:
# filter numpy array (print the even values as an example)
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

# method 1 : by your self
values = [False,True,False,True,False,True,False,True,False,True]
print(f"Method 1 : {np1[values]}")

# method 2 : by using loops
m2 = []
for element in np1:
    if element%2==0:
        m2.append(True)
    else:
        m2.append(False)
print(f"Method 2 : {np1[m2]}")

# method 3 : by using yhe power of numpy
m3 = np1 % 2 == 0
print(f"Method 3 : {np1[m3]}")



Method 1 : [ 2  4  6  8 10]
Method 2 : [ 2  4  6  8 10]
Method 3 : [ 2  4  6  8 10]


# Thanks